### ISSUE TITLE
Email links must point to www.ozfloodhelp.org.au and not www.ozfloodhelp.org.au

### ISSUE THREAD

**Issue by kuperov** [markryall/floodhousing#62]
All email links MUST point to www.ozfloodhelp.org.au AND NOT www.ozfloodhelp.org.

This is causing all email sent by the system to gmail to be sent to spam.

So, the shortlinks in the emails must point to the .au domain, and then be redirected as appropriate.

**Comment by quad** [comment]
Please explain this issue. We reverted the link because the domain for e-mails matches .org, and used HTTPS to avoid the double-redirect issue.

The spamassassin filter matches said that the URLs for .org and .org.au both trigger the young domain blacklists. But, that won't change by changing the URLs.

In short, explanation please?

**Comment by kuperov** [comment]
The app is being sent to hundreds of thousands of users as we speak. This needs to be fixed straight away. If you have any questions, don't hestitate to call 0402 024 304.

GMail is marking any emails with the string "ozfloodhelp.org" as spam.
It is not marking emails containing the string "ozfloodhelp.org.au" as spam.

**Comment by strongcoffee** [comment]
update to email to use ozfloodhelp.org.au link got updated and deployed today
